POST http://localhost:3000/posts
Content-Type: application/json

{
  "title": "Learn Perl",
  "postType": "post",
  "slug": "learn-perl",
  "postStatus": "draft",
  "content": "Hello world",
  "schema": "{\n  \"@context\": \"https://schema.org\",\n  \"@type\": \"BlogPosting\"\n}",
  "featuredImageUrl": "https://example.com/images/nestjs-guide.jpg",
  "publishOn": "2025-11-25T12:46:33+06:00",
  "tags": [9],
  "metaOptions": {
    "metaValue": "{\"sidebarEnabled\": true, \"footerActived\": false}"
  },
  "authorId": 1
}