POST http://localhost:3000/posts
Content-Type: application/json

{
  "title": "Learn MIcrosoft Azure",
  "postType": "post",
  "slug": "learn-microsoft-azure",
  "postStatus": "draft",
  "content": "Hello world",
  "schema": "{\n  \"@context\": \"https://schema.org\",\n  \"@type\": \"BlogPosting\"\n}",
  "featuredImageUrl": "https://example.com/images/nodejs-guide.jpg",
  "publishOn": "2026-01-14T05:55:52.349Z",
  "tags": [25],
  "metaOptions": {
    "metaValue": "{\"sidebarEnabled\": true, \"footerActived\": false}"
  },
  "authorId": 1
}