POST http://localhost:3000/tags
Content-Type: application/json

{
    "name": "Microsoft Azure",
    "description": "Microsoft Azure is a cloud computing platform.",
    "slug": "azure",
    "schema": "{}",
    "featuredImageUrl": "https://azure.microsoft.com/en-us/branding/azure-logo.svg"
}